name: Publish next plugin version

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Publish next plugin version to Gradle plugin portal
        env:
          GRADLE_PUBLISH_KEY: ${{ secrets.PUBLISH_KEY }}
          GRADLE_PUBLISH_SECRET: ${{ secrets.PUBLISH_SECRET }}
        run: ./gradlew :napt-gradle:publishPlugins --no-daemon
